name: Continuous Integration
description: Runs linting, code coverage, and dry build
runs:
  using: "composite"
  steps:
    - run: yarn install
      shell: bash
    - run: yarn bootstrap
      shell: bash
    - run: yarn build
      shell: bash
    - run: yarn flow-typed-install
      shell: bash
    - run: yarn flow
      shell: bash
    - run: yarn test --coverage
      shell: bash
    - run: echo "CODECOV_FLAGS=$(yarn node ./workspaces.js --ls-projects)" >> $GITHUB_ENV
      shell: bash
    - run: echo "${{ env.CODECOV_FLAGS }}"
      shell: bash
    - run: yarn build-storybook
      shell: bash