on:
  push:
    branches:
      - master
jobs:
  build:
    uses: ./.github/workflows/ci/bundle.yml
  test:
    needs: build
    uses: ./.github/workflows/ci/test.yml
  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: ./.github/actions/ci
      - uses: actions/download-artifact@v3
        with:
          name: bundles-${{env.GITHUB_SHA}}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: storybook-static