on:
  workflow_call:

jobs:
  setenv:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.ls_public_workspaces.outputs.workspaces }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - id: ls_public_workspaces
        run: echo "::set-output name=workspaces::$(yarn node ./workspaces.js --ls-public)"
        shell: bash
  lint:
    name: "Lint Sources"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
        shell: bash
      - run: yarn bootstrap
        shell: bash
      - uses: actions/download-artifact@v3
        with:
          name: bundles-${{ github.sha }}
      - run: yarn flow-typed-install
        shell: bash
      - run: yarn flow
        shell: bash
      - run: yarn lint
        shell: bash
  test:
    name: "Test Projects"
    runs-on: ubuntu-latest
    needs: setenv
    strategy:
      matrix:
        project: ${{ fromJSON(needs.setenv.outputs.workspaces) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn test --coverage --projects ${{ matrix.project }}
        shell: bash
