on:
  workflow_call:

jobs:
  lint:
    name: "Lint Sources"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
        shell: bash
      - run: yarn bootstrap
        shell: bash
      - uses: actions/download-artifact@v3
        with:
          name: bundles-${{ github.sha }}
      - run: yarn flow-typed-install
        shell: bash
      - run: yarn flow
        shell: bash
      - run: yarn lint
        shell: bash